install:
  - ps: . .\appveyor\install.ps1

build_script:
  - ps: . .\appveyor\build.ps1

test_script:
  - ps: . .\appveyor\test.ps1

artifacts:
  - path: $(APPVEYOR_PROJECT_NAME)\**\*.*
    name: PowerShellModule

for:
-
  branches:
    only:
    - "master"

  deploy_script:
  - ps: .\appveyor\master_deploy_scripts.ps1
